In [1]:
import pandas as pd
df=pd.DataFrame({'usn':[100,101,102],'name':['sham','joy','ram'],'marks':[100,89,99]})

In [2]:
df

usn  name  marks
0  100  sham    100
1  101   joy     89
2  102   ram     99

In [3]:
df['usn']

0    100
1    101
2    102
Name: usn, dtype: int64

In [4]:
df[['usn','name']]

usn  name
0  100  sham
1  101   joy
2  102   ram

In [5]:
df.loc[2]

usn      102
name     ram
marks     99
Name: 2, dtype: object

In [6]:
df[['usn','name','marks']]

usn  name  marks
0  100  sham    100
1  101   joy     89
2  102   ram     99

In [7]:
df.iloc[2]

usn      102
name     ram
marks     99
Name: 2, dtype: object

In [8]:
df.loc[[0,1],['usn','marks']]

usn  marks
0  100    100
1  101     89

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print("Type of array:",type(arr))

Type of array: <class 'numpy.ndarray'>


In [6]:
print("Dimension of array:",arr.ndim)

Dimension of array: 2


In [7]:
print("Shape of an array:",arr.shape)

Shape of an array: (2, 3)


In [8]:
print("Size of an array:",arr.size)

Size of an array: 6


In [9]:
print("Array stores elements of type",arr.dtype)

Array stores elements of type int32


In [10]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b=np.array((1,2,3))
b

array([1, 2, 3])

In [19]:
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
d=np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [22]:
e=np.full((3,3),6)
e

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [23]:
e=np.full((3,3),6,dtype='float')
e

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [24]:
e=np.full((3,3),6,dtype='int')
e

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [25]:
e=np.full((3,3),6,dtype='complex')
e

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [28]:
e=np.empty((2,3))
e

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
f=np.random.random((2,2))
f

array([[0.34912492, 0.53122889],
       [0.43435108, 0.26183549]])

In [35]:
g=np.arange(0,1000,10)
g

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [38]:
h=np.linspace(0,5,10)
h

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [44]:
arr=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [45]:
newarr=arr.reshape(2,2,3)
newarr

array([[[ 1,  2,  3],
        [ 4,  4,  5]],

       [[ 6,  7,  7],
        [ 8,  9, 10]]])

In [46]:
arr=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
newarr=arr.flatten()
newarr

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [47]:
a=np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [48]:
a+=5

In [49]:
a

array([[6, 7, 8, 9]])

In [50]:
a*=2

In [51]:
a

array([[12, 14, 16, 18]])

In [52]:
a

array([[12, 14, 16, 18]])

In [53]:
a-=2

In [54]:
a

array([[10, 12, 14, 16]])

In [55]:
print("elements subtracted by one",a-1)
a

elements subtracted by one [[ 9 11 13 15]]


array([[10, 12, 14, 16]])

In [56]:
a

array([[10, 12, 14, 16]])

In [57]:
a**2

array([[100, 144, 196, 256]], dtype=int32)

In [61]:
m=np.array([[5,6,7,8],[1,2,3,4],[1,9,6,3]])
m

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 9, 6, 3]])

In [62]:
m.max()

9

In [63]:
m.min()

1

m.sum()

In [64]:
m.sum()

55

In [65]:
m.max(axis=1)

array([8, 4, 9])

In [66]:
m.min(axis=1)

array([5, 1, 1])

In [67]:
m.max(axis=0)

array([5, 9, 7, 8])

In [68]:
m.min(axis=0)

array([1, 2, 3, 3])

In [73]:
a=np.array([[1,2],[4,5]])
b=np.array(([7,8],[10,11]))
a+b

array([[ 8, 10],
       [14, 16]])

In [75]:
a-b

array([[-6, -6],
       [-6, -6]])

In [76]:
a*b

array([[ 7, 16],
       [40, 55]])

In [74]:
a.dot(b)

array([[27, 30],
       [78, 87]])